version: '3'

services:

  github-ranking-spa:
    build:
      context: ./spa
    container_name: github-ranking-spa
    restart: unless-stopped
    env_file: ./.env
    environment: 
      NODE_ENV: $NODE_ENV
    ports:
      - "3000-3005:${DEV_SERVER_PORT}"
      - "35729:${LIVERELOAD_PORT}"
    volumes:
      - ./spa:/usr/src/app
    tty: true
